module.exports = {
    CREATE_CASE: 'CREATE_CASE',
    BULK_CREATE_CASE: 'BULK_CREATE_CASE',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',
    MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
    SUBMIT_STAGE: 'SUBMIT_STAGE',
    ADD_TOPIC: 'ADD_TOPIC',
    REMOVE_TOPIC: 'REMOVE_TOPIC',
    ADD_PARENT_TOPIC: 'ADD_PARENT_TOPIC',
    ADD_CORRESPONDENT: 'ADD_CORRESPONDENT',
    REMOVE_CORRESPONDENT: 'REMOVE_CORRESPONDENT'
};