module.exports = {
    CREATE_CASE: 'CREATE_CASE',
    BULK_CREATE_CASE: 'BULK_CREATE_CASE',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',
    MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
    SUBMIT_STAGE: 'SUBMIT_STAGE',
    ADD_TOPIC: 'ADD_TOPIC',
    REMOVE_TOPIC: 'REMOVE_TOPIC',
    ADD_CORRESPONDENT: 'ADD_CORRESPONDENT',
    ADD_MEMBER: 'ADD_MEMBER',
    SELECT_MEMBER: 'SELECT_MEMBER',
    IS_MEMBER: 'IS_MEMBER',
    REMOVE_CORRESPONDENT: 'REMOVE_CORRESPONDENT',
    UPDATE_CASE: 'UPDATE_CASE',
    ADD_STANDARD_LINE: 'ADD_STANDARD_LINE',
    ADD_TEMPLATE: 'ADD_TEMPLATE'
};