module.exports = {
    CREATE_CASE: 'CREATE_CASE',
    BULK_CREATE_CASE: 'BULK_CREATE_CASE',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',
    MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
    SUBMIT_STAGE: 'SUBMIT_STAGE'
};