pipeline:

    build-docker-image:
      group: lint-build-steps
      image: docker:17.09.1
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      commands:
        - docker build -t hocs-frontend .
      when:
        event: push

    lint:
      group: lint-build-steps
      image: node:14.15.4-alpine
      commands:
        - npm i eslint@7.20.0
        - npm run lint
      when:
        event: [push, pull_request]

    install-docker-image-latest:
      image: docker:17.09.1
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      secrets:
        - docker_password
      commands:
        - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
        - docker tag hocs-frontend quay.io/ukhomeofficedigital/hocs-frontend:latest
        - docker push quay.io/ukhomeofficedigital/hocs-frontend:latest
      when:
        branch: master
        event: push

    install-docker-image:
      image: docker:17.09.1
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      secrets:
        - docker_password
      commands:
        - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
        - docker tag hocs-frontend quay.io/ukhomeofficedigital/hocs-frontend:build-$${DRONE_BUILD_NUMBER}
        - export BRANCH_NAME_TAGFRIENDLY=`echo "$${DRONE_COMMIT_BRANCH}" | sed 's$/$_$g'` # sed can use any character as delimiter
        - docker tag hocs-frontend quay.io/ukhomeofficedigital/hocs-frontend:branch-$${BRANCH_NAME_TAGFRIENDLY}
        - docker push quay.io/ukhomeofficedigital/hocs-frontend:build-$${DRONE_BUILD_NUMBER}
        - docker push quay.io/ukhomeofficedigital/hocs-frontend:branch-$${BRANCH_NAME_TAGFRIENDLY}
      when:
        branch: [master, epic/*, hotfix/*]
        event: push

    sonar-scanner:
      image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.2
      when:
        event: [push, pull_request, tag]



    docker-semver-tag:
      image: quay.io/ukhomeofficedigital/hocs-version-bot:build-25
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
        - DOCKER_API_VERSION=1.37
      secrets:
        - github_password
        - docker_password
        - git_password
      commands:
        - /app/hocs-deploy --version=$${SEMVER} --serviceGitToken=$${GIT_PASSWORD} --service=hocs-frontend --gitToken=$${GITHUB_PASSWORD} --gitRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git" --environment=qa --dockerRepository=quay.io/ukhomeofficedigital --sourceBuild=$${IMAGE_VERSION} --registryUser=ukhomeofficedigital+hocs --registryPassword=$${DOCKER_PASSWORD}
      when:
        event: deployment
        environment: [cs-qa, wcs-qa, hocs-qax]

    clone-kube-project:
      image: plugins/git
      commands:
        - git clone https://github.com/UKHomeOffice/kube-hocs-frontend.git
      when:
        event: [push, deployment, tag]

    deploy-to-cs-dev-from-build-number:
      group: deploy-to-dev
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=cs
        - ENVIRONMENT=cs-dev
        - VERSION=build-${DRONE_BUILD_NUMBER}
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_dev_cs
      commands:
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        branch: master
        event: [push, tag]

    deploy-to-wcs-dev-from-build-number:
      group: deploy-to-dev
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=wcs
        - ENVIRONMENT=wcs-dev
        - VERSION=build-${DRONE_BUILD_NUMBER}
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_dev_wcs
      commands:
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        branch: master
        event: [push, tag]

    deployment:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - ENVIRONMENT=${DRONE_DEPLOY_TO}
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_dev_cs
        - hocs_frontend_demo_cs
        - hocs_frontend_dev_wcs
        - hocs_frontend_demo_wcs
        - poise_whitelist
      commands:
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: [cs-dev, cs-demo, wcs-dev, wcs-demo]

    deploy-to-qa-cs:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=cs
        - ENVIRONMENT=cs-qa
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_qa_cs
        - poise_whitelist
      commands:
        - source version.txt
        - echo $VERSION
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: cs-qa

    deploy-to-qa-wcs:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=wcs
        - ENVIRONMENT=wcs-qa
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_qa_wcs
        - poise_whitelist
      commands:
        - source version.txt
        - echo $VERSION
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: wcs-qa

    deploy-to-hocs-qax:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=cs
        - ENVIRONMENT=hocs-qax
        - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_qax
        - poise_whitelist
      commands:
        - source version.txt
        - echo $VERSION
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: hocs-qax

    deploy-to-prod-cs:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=cs
        - ENVIRONMENT=cs-prod
        - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_prod_cs
        - poise_whitelist
      commands:
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: cs-prod

    deploy-to-prod-wcs:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - DOMAIN=wcs
        - ENVIRONMENT=wcs-prod
        - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      secrets:
        - hocs_frontend_prod_wcs
        - poise_whitelist
      commands:
        - cd kube-hocs-frontend
        - ./deploy.sh
      when:
        event: deployment
        environment: wcs-prod
