---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_frontend_cs_qa
      POISE_IPS:
        from_secret: POISE_IPS
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to wcs-qa
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-qa
      KUBE_TOKEN:
        from_secret: hocs_frontend_wcs_qa
      POISE_IPS:
        from_secret: POISE_IPS
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_frontend_${DRONE_DEPLOY_TO/-/_}
      POISE_IPS:
        from_secret: POISE_IPS
      ACPTUNNEL_IPS:
        from_secret: ACPTUNNEL_IPS
    depends_on:
      - fetch and checkout
    when:
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_frontend_${DRONE_DEPLOY_TO/-/_}
      POISE_IPS:
        from_secret: POISE_IPS
    depends_on:
      - fetch and checkout
    when:
      target:
        include:
          - "*-prod"

---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: deploy to cs-dev
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      ENVIRONMENT: cs-dev
      VERSION: "${DRONE_TAG}"
      KUBE_TOKEN:
        from_secret: hocs_frontend_cs_dev
      POISE_IPS:
        from_secret: POISE_IPS
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone

  - name: deploy to wcs-dev
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      ENVIRONMENT: wcs-dev
      VERSION: "${DRONE_TAG}"
      KUBE_TOKEN:
        from_secret: hocs_frontend_wcs_dev
      POISE_IPS:
        from_secret: POISE_IPS
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone
