---

kind: pipeline
type: kubernetes
name: lint

steps:
- name: lint bash
  image: koalaman/shellcheck-alpine
  commands:
    - shellcheck *.sh
  depends_on:
    - clone

---

kind: pipeline
type: kubernetes
name: dry-run

# This pipeline runs deploy.sh with a few different ENVIRONMENTs set
# we run them with DRY_RUN=true so they don't do anything
#
# We're essentially checking that deploy.sh finishes with an exit code
# of zero, which will only happen if all accessed environment variables
# are defined correctly
#
# This Drone pipeline doesn't have access to actual kube tokens so there's
# no danger of actually deploying anywhere

steps:
- name: dry-run kd dev
  image: quay.io/ukhomeofficedigital/kd
  environment:
    DRY_RUN: true
    VERSION: test
    ENVIRONMENT: wcs-dev
    KUBE_TOKEN: test
    POISE_IPS: "127.0.0.1/32"
    ACPTUNNEL_IPS: "127.0.0.1/32"
  commands:
    - bash -x deploy.sh
  depends_on:
    - clone

- name: dry-run kd prod
  image: quay.io/ukhomeofficedigital/kd
  environment:
    DRY_RUN: true
    VERSION: test
    ENVIRONMENT: cs-prod
    KUBE_TOKEN: test
    POISE_IPS: "127.0.0.1/32"
    ACPTUNNEL_IPS: "127.0.0.1/32"
  commands:
    - bash -x deploy.sh
  depends_on:
    - clone

...
