apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hocs-frontend
  name: hocs-frontend
spec:
  maxReplicas: 2
  minReplicas: {{.REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hocs-frontend
  targetCPUUtilizationPercentage: 24
