---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-external
    stable.k8s.psg.io/kcm.provider: http
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        large_client_header_buffers 4 32k
      }
  labels:
    stable.k8s.psg.io/kcm.class: default
  name: hocs-frontend
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-frontend
          servicePort: 443
        path: /   
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-frontend-external-tls
