---
{{ if .INTERNAL_DOMAIN_NAME }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "52m"
    kubernetes.io/ingress.class: nginx-internal
    ingress.kubernetes.io/proxy-buffer-size: 128k
    ingress.kubernetes.io/server-snippets: |
      client_header_buffer_size     8k;
      large_client_header_buffers   4 128k;
  name: hocs-frontend-internal
  labels:
    # internal ingresses can't use http01 as Let's Encrypt can't see it
    cert-manager.io/solver: route53
spec:
  rules:
  - host: {{.INTERNAL_DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-frontend
          servicePort: 443
        path: /
      - backend:
          serviceName: hocs-audit
          servicePort: 443
        path: /export

  tls:
  - hosts:
    - {{.INTERNAL_DOMAIN_NAME}}
    secretName: hocs-frontend-internal-tls-cert
{{ end }}
