---
apiVersion: apps/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "52m"
    kubernetes.io/ingress.class: nginx-external
    stable.k8s.psg.io/kcm.provider: http
    ingress.kubernetes.io/proxy-buffer-size: 128k
    ingress.kubernetes.io/server-snippets: |
      client_header_buffer_size     8k;
      large_client_header_buffers   4 128k;
  labels:
    stable.k8s.psg.io/kcm.class: default
  name: hocs-frontend
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-frontend
          servicePort: 443
        path: /
      - backend:
          serviceName: hocs-audit
          servicePort: 443
        path: /export

  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-frontend-external-tls
