---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress
  namespace: {{.KUBE_NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      name: hocs-frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - port: 10443
      protocol: TCP
  egress:
    - {}