---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-frontend
  name: hocs-frontend
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  - name: http
    port: 80
    targetPort: 8081  
  selector:
    name: hocs-frontend
