const types = {
    UPDATE_FORM: 'UPDATE_FORM',
    UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    CANCEL: 'CANCEL',
    SET_PHASE: 'SET_PHASE',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    REDIRECTED: 'REDIRECTED',
    REDIRECT: 'REDIRECT'
};

export default types;