const types = {
    CANCEL: 'CANCEL',
    REDIRECT: 'REDIRECT',
    REDIRECTED: 'REDIRECTED',
    SET_ERROR: 'SET_ERROR',
    UNSET_ERROR: 'UNSET_ERROR',
    UNSET_FORM: 'UNSET_FORM',
    UPDATE_API_STATUS: 'UPDATE_API_STATUS',
    CLEAR_API_STATUS: 'CLEAR_API_STATUS',
    UPDATE_PAGE_META: 'UPDATE_PAGE_META',
    UPDATE_FORM: 'UPDATE_FORM',
    UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
    UPDATE_FORM_ERRORS: 'UPDATE_FORM_ERRORS',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
    CLEAR_DASHBOARD: 'CLEAR_DASHBOARD',
    UPDATE_WORKSTACK: 'UPDATE_WORKSTACK',
    CLEAR_WORKSTACK: 'CLEAR_WORKSTACK',
    UNSET_CASE_SUMMARY: 'UNSET_CASE_SUMMARY',
    UNSET_CASE_NOTES: 'UNSET_CASE_NOTES',
    PASS_FORWARD_PROPS: 'PASS_FORWARD_PROPS'
};

export default types;