const types = {
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    BULK_ADD_DOCUMENT: 'BULK_ADD_DOCUMENT',
    CANCEL: 'CANCEL',
    REDIRECT: 'REDIRECT',
    REDIRECTED: 'REDIRECTED',
    SET_PHASE: 'SET_PHASE',
    UPDATE_FORM: 'UPDATE_FORM',
    UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
    UPDATE_FORM_ERRORS: 'UPDATE_FORM_ERRORS',
    UPDATE_LOCATION: 'UPDATE_LOCATION'
};

export default types;