---
hocs-generic-service:

  isProd: false

  autoscale:
    enabled: false

  deployment:
    replicas: 1
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-08:00 Europe/London,Mon-Sun 18:00-24:00 Europe/London"

  keycloak:
    realm: https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod
    domain: cs-notprod.homeoffice.gov.uk

  ingress:
    external:
      enabled: true
      host: dev.{{ .Values.clusterPrefix }}-notprod.homeoffice.gov.uk
    internal:
      enabled: true
      host: dev.internal.{{ .Values.clusterPrefix }}-notprod.homeoffice.gov.uk

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    env:
      isNotProd: 1
