---
hocs-generic-service:

  deployment:
    annotations:
      downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-08:00 Europe/London,Mon-Fri 18:00-24:00 Europe/London"

  clusterPrefix: cs

  keycloak:
    realm: https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod
    domain: cs-notprod.homeoffice.gov.uk

  ingress:
    external:
      enabled: true
      host: dev.cs-notprod.homeoffice.gov.uk
    internal:
      enabled: true
      host: dev.internal.cs-notprod.homeoffice.gov.uk

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    env:
      isNotProd: '1'
