---
hocs-generic-service:

  ingress:
    external:
      host: demo.{{ .Values.clusterPrefix }}-notprod.homeoffice.gov.uk
    internal:
      host: demo.internal.{{ .Values.clusterPrefix }}-notprod.homeoffice.gov.uk
