---
hocs-generic-service:

  autoscale:
    enabled: false

  deployment:
    replicas: 1
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-08:00 Europe/London,Mon-Sun 18:00-24:00 Europe/London"
