name: 'Docker Build Tag'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag-npm.yml@v3
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-frontend'
      node-version: 18
    secrets: inherit
