name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/test-javascript.yml@6561bc5affdaf4895ea070bb6b62a424567766e3
