name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/test-javascript.yml@v1
    with:
      node-version-matrix: '[ "16.x" , "18.x" ]'
