name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/hocs-ci-infrastructure/.github/workflows/test-javascript.yml@f86584b9b75e4e5d7febc900761250f002517689
