name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/test-javascript.yml@7de2ab0ff74942468fc3bdd61955cdf73a80f1d6
    with:
      node-version-matrix: '[ "16.x" , "18.x" ]'
